baseURL = "https://allyson.cloud/"
languageCode = "en-us"
title = "Allyson Oliveira"
theme = "hyde-hyde"

[params]
description = "Churrasqueiro nos finais de semana e desenvolvendo infraestrutura de segunda a sexta"

[params.social]  
  twitter = "asoliveira"
  github = "allysono"
  linkedin = "allysonoliveira"
  telegram = "sre_allyson"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
