baseURL = "https://allyson.cloud/"
languageCode = "en-us"
title = "Allyson Oliveira"
theme = "soho"
googleAnalytics = "UA-162896323-1"

[params]
description = "Arquiteto de soluções na AWS | DevSecOps"
profilePicture="/img/profile.png"
highlightjs = true
highlightjsstyle = "github"
disqusShortname = "allyshow"

# sidebar, copyright & license
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "/allysonoliveira"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "/asoliveira"

#[params.social]  
#  twitter = "asoliveira"
#  github = "allysono"
#  linkedin = "allysonoliveira"
#  telegram = "sre_allyson"
#  email = "asoliveira@outlook.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Fale comigo!"
    identifier = "Sobre Mim"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Blogroll"
    identifier = "Blogroll"
    weight = 200
    url = "/blogroll/"
[[menu.main]]
    name = "Projetos"
    identifier = "Projetos"
    weight = 200
    url = "/projetos/"