baseURL = "https://example.org/"
languageCode = "en-us"
title = "Allyson Oliveira"
theme = "hyde-hyde"

[params]
description = "Churrasqueiro nos finais de semana e desenvolvendo infraestrutura de segunda a sexta"

[params.social]  
  twitter = "asoliveira"
  github = "allysono"
  linkedin = "allysonoliveira"
  telegram = "sre_allyson"
  