baseURL = "https://example.org/"
languageCode = "en-us"
title = "Allyson de Souza Oliveira"
theme = "hyde-hyde"

[params]
  description = "SRE/Devops"
  twitterName = "asoliveira"
  githubName = "allysono"
  linkedinName = "allysonoliveira"
