baseURL = "https://allyson.cloud/"
languageCode = "en-us"
title = "Allyson Oliveira"
theme = "hyde-hyde"
googleAnalytics = "UA-162896323-1"

[params]
description = "Churrasqueiro nos finais de semana e arquitetando infraestrutura em cloud de segunda a sexta!"
authorimage="/img/profile.jpeg"
highlightjs = true
highlightjsstyle = "github"
disqusShortname = "allyshow"

# sidebar, copyright & license
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[params.social]  
  twitter = "asoliveira"
  github = "allysono"
  linkedin = "allysonoliveira"
  telegram = "sre_allyson"
  email = "asoliveira@outlook.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Sobre Mim"
    identifier = "Sobre Mim"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Blogroll"
    identifier = "Blogroll"
    weight = 200
    url = "/blogroll/"
[[menu.main]]
    name = "Projetos"
    identifier = "Projetos"
    weight = 200
    url = "/projetos/"